version: "3.9"
services:
  frontend:
    build: . # Contexto de build é a pasta atual (onde está o Dockerfile)
    ports:
      - "80:80"
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./backend/server
    ports:
      - "8000:8000"