version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"    # Porta para o Nginx (frontend)
      - "8000:8000" # Porta para o backend FastAPI
    volumes:
      - ./backend/server:/app/backend  # Para desenvolvimento (hot reload)
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped 